### ISSUE TITLE
Passwordハッシュ化関係の情報整理と実装反映

### ISSUE THREAD

**Issue by na2na-p** [ih14c-13-14/artist-backend#10]
# What

バックエンドでパスワードをハッシュ化したら何文字になるか調査する

# Why

DBスキーマの厳格化のため。
具体的には`users.password`の文字数決定に利用する。
確定したら`@db.VarChar(255)`ではなく、`@db.Char(number)`のように書いてPRを出す

**Comment by Issiki0416** [comment]
bcryptを使いたいと思う〜。文字数は60文字みたいね

[参照]
- https://tomokazu-kozuma.com/how-to-use-bcrypt-with-node-js/#:~:text=bcrypt%E3%81%AF60%E6%96%87%E5%AD%97%E3%81%AE%E3%83%8F%E3%83%83%E3%82%B7%E3%83%A5%E5%80%A4%E3%82%92%E7%94%9F%E6%88%90%E3%81%97%E3%81%BE%E3%81%99%E3%80%82

**Comment by na2na-p** [comment]
公式もそう言ってるし60で確定でよさそう

https://github.com/kelektiv/node.bcrypt.js#:~:text=Resultant%20hashes%20will%20be%2060%20characters%20long%20and%20they%20will%20include%20the%20salt%20among%20other%20parameters%2C%20as%20follows%3A

@Issiki0416 Prismaのスキーマに更新加えてPR出してもらえますか？

**Comment by Issiki0416** [comment]
了解です！
