### ISSUE TITLE
fix: Tokenテーブルの修正

### ISSUE THREAD

**Issue by Issiki0416** [ih14c-13-14/artist-backend#56]
<img width="545" alt="image" src="https://github.com/ih14c-13-14/artist-backend/assets/96870513/9aa72da3-6e43-40fa-a5c5-e7682b429d2a">   

- テーブル名を小文字に修正
-   `create_at  DateTime @default(now()) @db.Timestamp(6)`
- ` updated_at DateTime @updatedAt @db.Timestamp(6)`
- usersIdのカラム名の修正。`user_id`に統一

**Comment by na2na-p** [comment]
Resolved At #57
